import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  poweredByHeader: false,
  reactStrictMode: true,
  // The Mongo driver is server-only; keep it out of any client bundle graph.
  serverExternalPackages: ["mongodb"],
  async headers() {
    return [
      {
        source: "/api/:path*",
        headers: [{ key: "Cache-Control", value: "no-store, max-age=0" }],
      },
      {
        // A2OJ datasets are regenerated by the scrapers, not per-request.
        source: "/data/:path*",
        headers: [
          { key: "Cache-Control", value: "public, max-age=3600, s-maxage=86400" },
        ],
      },
      {
        // The coach publishes a new static plan during an active session. This
        // more-specific rule comes last so it overrides the dataset cache above.
        source: "/data/coach/:path*",
        headers: [
          {
            key: "Cache-Control",
            value: "no-store, max-age=0, must-revalidate",
          },
        ],
      },
    ];
  },
};

export default nextConfig;
